-- ============================================================
-- FlashCards – Seed Data: words
-- Ejecutar DESPUÉS de supabase-schema.sql
-- ============================================================

BEGIN;

-- ========================
-- Nivel: A1
-- ========================
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 1, 'house', '/haʊs/', '🏠', 'Noun', 'casa', ARRAY['I live in a small house.', 'The house has three bedrooms.', 'Her house is near the park.', 'We painted the house white.', 'They bought a new house last year.', 'The house is very old.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 2, 'water', '/ˈwɔːtər/', '💧', 'Noun', 'agua', ARRAY['Can I have a glass of water?', 'The water is very cold.', 'I drink water every day.', 'There is no water in the bottle.', 'The children are playing in the water.', 'We need clean water to cook.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 3, 'food', '/fuːd/', '🍽️', 'Noun', 'comida', ARRAY['The food is delicious.', 'We need to buy food for dinner.', 'Italian food is my favorite.', 'There is no food in the fridge.', 'She loves healthy food.', 'The food at this restaurant is great.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 4, 'family', '/ˈfæm.əl.i/', '👨‍👩‍👧‍👦', 'Noun', 'familia', ARRAY['My family is very big.', 'I love my family.', 'We visit our family on Sundays.', 'Her family lives in Spain.', 'Family is the most important thing.', 'The whole family went on vacation.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 5, 'friend', '/frɛnd/', '🤝', 'Noun', 'amigo/a', ARRAY['She is my best friend.', 'I met a new friend at school.', 'My friend lives in London.', 'He is a very good friend.', 'I called my friend yesterday.', 'We have been friends for ten years.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 6, 'school', '/skuːl/', '🏫', 'Noun', 'escuela', ARRAY['I go to school every day.', 'The school is near my house.', 'She likes her new school.', 'School starts at eight o''clock.', 'The children walk to school.', 'He teaches at a big school.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 7, 'book', '/bʊk/', '📖', 'Noun', 'libro', ARRAY['I am reading a good book.', 'This book is very interesting.', 'She bought a new book yesterday.', 'The book is on the table.', 'He writes books for children.', 'Can I borrow your book?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 8, 'car', '/kɑːr/', '🚗', 'Noun', 'coche / carro', ARRAY['My car is blue.', 'He drives his car to work.', 'The car is very fast.', 'We bought a new car.', 'The car is parked outside.', 'She washes her car every weekend.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 9, 'dog', '/dɒɡ/', '🐕', 'Noun', 'perro', ARRAY['I have a big dog.', 'The dog is very friendly.', 'My dog likes to play in the park.', 'She walks her dog every morning.', 'The dog is sleeping on the sofa.', 'We adopted a dog last month.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 10, 'cat', '/kæt/', '🐱', 'Noun', 'gato', ARRAY['The cat is on the bed.', 'My cat is black and white.', 'She has two cats at home.', 'The cat likes to drink milk.', 'Our cat is very lazy.', 'The cat caught a mouse.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 11, 'money', '/ˈmʌn.i/', '💰', 'Noun', 'dinero', ARRAY['I don''t have enough money.', 'She saves money every month.', 'Money is not everything.', 'He lost his money at the market.', 'How much money do you need?', 'They spend a lot of money on food.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 12, 'city', '/ˈsɪt.i/', '🏙️', 'Noun', 'ciudad', ARRAY['I live in a big city.', 'The city is very noisy.', 'New York is a famous city.', 'She moved to a new city.', 'The city center is beautiful.', 'There are many people in this city.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 13, 'phone', '/foʊn/', '📱', 'Noun', 'teléfono', ARRAY['My phone is broken.', 'Can I use your phone?', 'She bought a new phone.', 'The phone is ringing.', 'I lost my phone yesterday.', 'He always looks at his phone.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 14, 'morning', '/ˈmɔːr.nɪŋ/', '🌅', 'Noun', 'mañana', ARRAY['I wake up early in the morning.', 'Good morning! How are you?', 'The morning is cold today.', 'She runs every morning.', 'We have class in the morning.', 'The sun rises in the morning.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 15, 'night', '/naɪt/', '🌙', 'Noun', 'noche', ARRAY['Good night! Sleep well.', 'The night is very dark.', 'I study at night.', 'We went out last night.', 'The stars shine at night.', 'She works at night.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 16, 'doctor', '/ˈdɒk.tər/', '👨‍⚕️', 'Noun', 'doctor/a', ARRAY['I need to see a doctor.', 'The doctor is very nice.', 'She wants to be a doctor.', 'The doctor gave me medicine.', 'My doctor says I am healthy.', 'He went to the doctor yesterday.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 17, 'teacher', '/ˈtiːtʃ.ər/', '👩‍🏫', 'Noun', 'profesor/a', ARRAY['My teacher is very kind.', 'The teacher explains very well.', 'She is an English teacher.', 'The teacher gave us homework.', 'I like my new teacher.', 'He became a teacher last year.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 18, 'table', '/ˈteɪ.bəl/', '🪑', 'Noun', 'mesa', ARRAY['The book is on the table.', 'We eat dinner at the table.', 'She cleaned the table after lunch.', 'There are four chairs at the table.', 'He put his keys on the table.', 'The table is made of wood.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 19, 'door', '/dɔːr/', '🚪', 'Noun', 'puerta', ARRAY['Please close the door.', 'The door is open.', 'Someone is knocking on the door.', 'I locked the door before leaving.', 'The door is made of wood.', 'Open the door, please!']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 20, 'window', '/ˈwɪn.doʊ/', '🪟', 'Noun', 'ventana', ARRAY['Open the window, please.', 'I can see the garden from the window.', 'The window is broken.', 'She closed the window because it was cold.', 'The bird is sitting on the window.', 'There are three windows in this room.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 21, 'eat', '/iːt/', '🍴', 'Verb', 'comer', ARRAY['I eat breakfast at seven.', 'What do you want to eat?', 'She eats lunch at school.', 'We ate pizza last night.', 'He doesn''t eat meat.', 'The children eat a lot of fruit.'], 'ate', '/eɪt/', 'eaten', '/ˈiːt.ən/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 22, 'drink', '/drɪŋk/', '🥤', 'Verb', 'beber', ARRAY['I drink coffee every morning.', 'Would you like something to drink?', 'She drinks a lot of water.', 'He drank all the juice.', 'We drink tea in the afternoon.', 'Don''t drink too much soda.'], 'drank', '/dræŋk/', 'drunk', '/drʌŋk/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 23, 'sleep', '/sliːp/', '😴', 'Verb', 'dormir', ARRAY['I sleep eight hours every night.', 'The baby is sleeping.', 'She slept very well last night.', 'He can''t sleep without a pillow.', 'I need to sleep more.', 'The dog sleeps on the floor.'], 'slept', '/slɛpt/', 'slept', '/slɛpt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 24, 'go', '/ɡoʊ/', '🚶', 'Verb', 'ir', ARRAY['I go to work every day.', 'Where do you want to go?', 'She goes to the gym on Mondays.', 'We went to the beach yesterday.', 'He has gone home.', 'Let''s go to the park!'], 'went', '/wɛnt/', 'gone', '/ɡɒn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 25, 'come', '/kʌm/', '👋', 'Verb', 'venir', ARRAY['Come here, please.', 'She comes to class every day.', 'He came late to the meeting.', 'Can you come to my party?', 'They came from Mexico.', 'The bus is coming.'], 'came', '/keɪm/', 'come', '/kʌm/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 26, 'see', '/siː/', '👀', 'Verb', 'ver', ARRAY['I can see the mountains from here.', 'Did you see the movie?', 'She saw her friend at the store.', 'I want to see you tomorrow.', 'He has never seen the ocean.', 'Can you see that bird?'], 'saw', '/sɔː/', 'seen', '/siːn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 27, 'know', '/noʊ/', '🧠', 'Verb', 'saber / conocer', ARRAY['I know the answer.', 'Do you know her name?', 'She knows how to cook.', 'He didn''t know about the party.', 'I know this city very well.', 'They have known each other for years.'], 'knew', '/njuː/', 'known', '/noʊn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 28, 'want', '/wɒnt/', '🙏', 'Verb', 'querer', ARRAY['I want a glass of water.', 'What do you want for dinner?', 'She wants to learn English.', 'He wanted to go home early.', 'Do you want to come with us?', 'They don''t want to wait.'], 'wanted', '/ˈwɒn.tɪd/', 'wanted', '/ˈwɒn.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 29, 'like', '/laɪk/', '❤️', 'Verb', 'gustar', ARRAY['I like chocolate ice cream.', 'She likes to read books.', 'Do you like this song?', 'He likes playing soccer.', 'We liked the movie a lot.', 'They don''t like cold weather.'], 'liked', '/laɪkt/', 'liked', '/laɪkt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 30, 'work', '/wɜːrk/', '💼', 'Noun/Verb', 'trabajo / trabajar', ARRAY['I work in an office.', 'She works from Monday to Friday.', 'He worked very hard yesterday.', 'Where do you work?', 'I have a lot of work today.', 'They work together as a team.'], 'worked', '/wɜːrkt/', 'worked', '/wɜːrkt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 31, 'talk', '/tɔːk/', '🗣️', 'Verb', 'hablar', ARRAY['Can we talk for a minute?', 'She talks very fast.', 'He talked to his boss yesterday.', 'I like to talk with my friends.', 'Don''t talk during the class.', 'We talked on the phone last night.'], 'talked', '/tɔːkt/', 'talked', '/tɔːkt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 32, 'give', '/ɡɪv/', '🎁', 'Verb', 'dar', ARRAY['Can you give me a pen?', 'She gave me a present.', 'I want to give you something.', 'He gives money to charity.', 'They gave us good advice.', 'Please give me your number.'], 'gave', '/ɡeɪv/', 'given', '/ˈɡɪv.ən/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 33, 'take', '/teɪk/', '✋', 'Verb', 'tomar / llevar', ARRAY['Take your umbrella, it''s raining.', 'She took the bus to school.', 'Can I take a photo?', 'He takes a shower every morning.', 'I took my dog to the vet.', 'Please take a seat.'], 'took', '/tʊk/', 'taken', '/ˈteɪ.kən/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 34, 'make', '/meɪk/', '🔨', 'Verb', 'hacer / preparar', ARRAY['She makes coffee every morning.', 'I made dinner last night.', 'He makes beautiful drawings.', 'Can you make a cake?', 'We made a big mistake.', 'They make shoes in this factory.'], 'made', '/meɪd/', 'made', '/meɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 35, 'buy', '/baɪ/', '🛒', 'Verb', 'comprar', ARRAY['I want to buy a new shirt.', 'She bought a present for her mom.', 'Where did you buy that?', 'We need to buy some milk.', 'He buys coffee every day.', 'They bought a new house.'], 'bought', '/bɔːt/', 'bought', '/bɔːt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 36, 'play', '/pleɪ/', '⚽', 'Verb', 'jugar / tocar', ARRAY['The children play in the park.', 'He plays guitar very well.', 'She played tennis yesterday.', 'Do you want to play a game?', 'We played soccer after school.', 'I don''t play video games often.'], 'played', '/pleɪd/', 'played', '/pleɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 37, 'help', '/hɛlp/', '🆘', 'Noun/Verb', 'ayuda / ayudar', ARRAY['Can you help me, please?', 'She helped me with my homework.', 'I need help with this box.', 'He always helps his neighbors.', 'Thank you for your help.', 'We helped clean the house.'], 'helped', '/hɛlpt/', 'helped', '/hɛlpt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 38, 'read', '/riːd/', '📚', 'Verb', 'leer', ARRAY['I like to read before bed.', 'She reads the newspaper every day.', 'He read the whole book in one day.', 'Can you read this for me?', 'We read a story in class.', 'They love to read magazines.'], 'read', '/rɛd/', 'read', '/rɛd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 39, 'write', '/raɪt/', '✍️', 'Verb', 'escribir', ARRAY['I write in my diary every night.', 'She wrote a letter to her friend.', 'Can you write your name here?', 'He writes very well.', 'We have written ten pages.', 'Please write the answer on the board.'], 'wrote', '/roʊt/', 'written', '/ˈrɪt.ən/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 40, 'listen', '/ˈlɪs.ən/', '👂', 'Verb', 'escuchar', ARRAY['Listen to the teacher, please.', 'I like to listen to music.', 'She listened carefully to the instructions.', 'He never listens to me.', 'We listened to a podcast yesterday.', 'Listen! Do you hear that sound?'], 'listened', '/ˈlɪs.ənd/', 'listened', '/ˈlɪs.ənd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 41, 'big', '/bɪɡ/', '🐘', 'Adjective', 'grande', ARRAY['The elephant is very big.', 'She lives in a big house.', 'He has a big family.', 'This is a big problem.', 'The city is too big for me.', 'I want a big piece of cake.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 42, 'small', '/smɔːl/', '🐜', 'Adjective', 'pequeño/a', ARRAY['The ant is very small.', 'She has a small dog.', 'Our apartment is small but nice.', 'He lives in a small town.', 'This shirt is too small for me.', 'I need a small bag.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 43, 'good', '/ɡʊd/', '👍', 'Adjective', 'bueno/a', ARRAY['This is a very good book.', 'She is a good student.', 'The weather is good today.', 'He is a good friend.', 'Good morning! How are you?', 'The food tastes really good.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 44, 'bad', '/bæd/', '👎', 'Adjective', 'malo/a', ARRAY['The weather is bad today.', 'I feel bad about what happened.', 'That was a bad idea.', 'The milk smells bad.', 'He had a bad day at work.', 'This is not bad at all.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 45, 'happy', '/ˈhæp.i/', '😊', 'Adjective', 'feliz / contento', ARRAY['I am very happy today.', 'She looks happy in the photo.', 'The children are happy at the park.', 'He is happy with his new job.', 'Happy birthday to you!', 'We are happy to see you.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 46, 'sad', '/sæd/', '😢', 'Adjective', 'triste', ARRAY['She feels sad today.', 'The movie was very sad.', 'I am sad because my friend left.', 'He looks sad — what happened?', 'Don''t be sad, things will get better.', 'It was a sad story.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 47, 'hot', '/hɒt/', '🔥', 'Adjective', 'caliente / caluroso', ARRAY['The coffee is very hot.', 'It is hot outside today.', 'Be careful, the pan is hot.', 'I don''t like hot weather.', 'The soup is too hot to eat.', 'Summer is very hot in this city.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 48, 'cold', '/koʊld/', '❄️', 'Adjective', 'frío', ARRAY['It is very cold today.', 'The water is too cold.', 'I feel cold without my jacket.', 'Winter is very cold here.', 'She has cold hands.', 'Would you like a cold drink?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 49, 'new', '/njuː/', '✨', 'Adjective', 'nuevo/a', ARRAY['I have a new phone.', 'She started a new job.', 'Is there anything new?', 'We moved to a new apartment.', 'He bought a new car.', 'I want to learn new things.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 50, 'old', '/oʊld/', '👴', 'Adjective', 'viejo/a / antiguo', ARRAY['My grandfather is very old.', 'This is an old building.', 'She has an old car.', 'How old are you?', 'The old house needs repairs.', 'He is my old friend from school.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 51, 'easy', '/ˈiː.zi/', '✅', 'Adjective', 'fácil', ARRAY['This exercise is easy.', 'English is not easy to learn.', 'The test was very easy.', 'It''s easy to make mistakes.', 'She found an easy solution.', 'Cooking pasta is easy.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 52, 'difficult', '/ˈdɪf.ɪ.kəlt/', '😰', 'Adjective', 'difícil', ARRAY['This question is very difficult.', 'Math is difficult for me.', 'The exam was really difficult.', 'It''s difficult to understand him.', 'Learning a new language is difficult.', 'She solved a difficult problem.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 53, 'beautiful', '/ˈbjuː.tɪ.fəl/', '🌸', 'Adjective', 'hermoso/a / bonito/a', ARRAY['The sunset is beautiful.', 'She has a beautiful smile.', 'What a beautiful day!', 'The flowers are very beautiful.', 'He painted a beautiful picture.', 'This is a beautiful city.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 54, 'hungry', '/ˈhʌŋ.ɡri/', '🤤', 'Adjective', 'hambriento / con hambre', ARRAY['I am very hungry.', 'Are you hungry? Let''s eat.', 'The children are always hungry.', 'She was too hungry to wait.', 'I get hungry in the afternoon.', 'He is hungry because he skipped lunch.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 55, 'tired', '/taɪərd/', '😩', 'Adjective', 'cansado/a', ARRAY['I am very tired today.', 'She looks tired after work.', 'He was too tired to cook.', 'The children are tired after playing.', 'I''m tired of waiting.', 'We were tired but happy.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 56, 'very', '/ˈvɛr.i/', '💯', 'Adverb', 'muy', ARRAY['She is very smart.', 'The movie was very good.', 'I am very happy today.', 'It is very cold outside.', 'He runs very fast.', 'Thank you very much!']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 57, 'always', '/ˈɔːl.weɪz/', '🔁', 'Adverb', 'siempre', ARRAY['She always arrives on time.', 'I always eat breakfast.', 'He is always happy.', 'We always go to the same restaurant.', 'They always help each other.', 'I always forget my keys.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 58, 'never', '/ˈnɛv.ər/', '🚫', 'Adverb', 'nunca', ARRAY['I never eat fast food.', 'She never arrives late.', 'He has never been to Paris.', 'We never watch TV in the morning.', 'I will never forget this day.', 'They never argue.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 59, 'sometimes', '/ˈsʌm.taɪmz/', '🤷', 'Adverb', 'a veces', ARRAY['I sometimes go to the gym.', 'She sometimes works on Saturdays.', 'Sometimes I feel tired.', 'He sometimes forgets his lunch.', 'We sometimes eat out on Fridays.', 'Sometimes it rains in the afternoon.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 60, 'here', '/hɪər/', '📍', 'Adverb', 'aquí', ARRAY['Come here, please.', 'I live here.', 'She is not here right now.', 'The bus stops here.', 'We like it here.', 'Put the box here.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 61, 'today', '/təˈdeɪ/', '📅', 'Adverb', 'hoy', ARRAY['Today is a beautiful day.', 'What are you doing today?', 'I have a meeting today.', 'She is not working today.', 'We start school today.', 'The store is closed today.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 62, 'hello', '/həˈloʊ/', '👋', 'Common Phrase', 'hola', ARRAY['Hello! How are you?', 'Hello, my name is Anna.', 'She said hello to everyone.', 'Hello, can I help you?', 'He waved and said hello.', 'Hello! Nice to meet you.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 63, 'goodbye', '/ɡʊdˈbaɪ/', '👋', 'Common Phrase', 'adiós', ARRAY['Goodbye! See you tomorrow.', 'She said goodbye to her friends.', 'It was hard to say goodbye.', 'Goodbye and take care.', 'He waved goodbye from the window.', 'We said goodbye at the airport.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 64, 'please', '/pliːz/', '🙏', 'Common Phrase', 'por favor', ARRAY['Can you help me, please?', 'Please sit down.', 'A glass of water, please.', 'Please be quiet.', 'Could you repeat that, please?', 'Please close the door.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 65, 'thank you', '/θæŋk juː/', '🙏', 'Common Phrase', 'gracias', ARRAY['Thank you for your help.', 'Thank you very much!', 'She said thank you to the waiter.', 'Thank you for coming.', 'I want to say thank you.', 'Thank you, that''s very kind.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 66, 'sorry', '/ˈsɒr.i/', '😔', 'Common Phrase', 'lo siento / disculpa', ARRAY['I''m sorry I''m late.', 'Sorry, I didn''t hear you.', 'She said sorry for the mistake.', 'I''m sorry about your loss.', 'Sorry, can you say that again?', 'He felt sorry for what he did.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 67, 'how are you', '/haʊ ɑːr juː/', '😊', 'Common Phrase', '¿cómo estás?', ARRAY['Hello! How are you?', 'How are you today?', 'How are you doing?', 'Hey, how are you? Long time no see!', 'How are you feeling now?', 'Hi! How are you this morning?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 68, 'I don''t understand', '/aɪ doʊnt ˌʌndərˈstænd/', '😕', 'Common Phrase', 'no entiendo', ARRAY['I don''t understand this word.', 'Sorry, I don''t understand.', 'I don''t understand the question.', 'She said she doesn''t understand.', 'I don''t understand what you mean.', 'Can you explain? I don''t understand.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 69, 'how much', '/haʊ mʌtʃ/', '💲', 'Common Phrase', '¿cuánto cuesta?', ARRAY['How much is this shirt?', 'How much does it cost?', 'How much money do you have?', 'How much water do we need?', 'How much is the ticket?', 'How much do I owe you?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 70, 'where is', '/wɛər ɪz/', '🗺️', 'Common Phrase', '¿dónde está?', ARRAY['Where is the bathroom?', 'Where is the bus stop?', 'Excuse me, where is the bank?', 'Where is my phone?', 'Do you know where is the hospital?', 'Where is the nearest supermarket?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 71, 'I need', '/aɪ niːd/', '🤲', 'Common Phrase', 'necesito', ARRAY['I need help with this.', 'I need to go now.', 'I need a glass of water.', 'I need to study more.', 'I need your advice.', 'I need to rest for a while.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 72, 'I like', '/aɪ laɪk/', '😍', 'Common Phrase', 'me gusta', ARRAY['I like this restaurant.', 'I like to travel.', 'I like your new haircut.', 'I like coffee with milk.', 'I like playing with my dog.', 'I like this song a lot.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 73, 'excuse me', '/ɪkˈskjuːz miː/', '🙋', 'Common Phrase', 'disculpe / con permiso', ARRAY['Excuse me, where is the exit?', 'Excuse me, can I ask a question?', 'Excuse me, is this seat taken?', 'Excuse me, what time is it?', 'Excuse me, I need to pass.', 'Excuse me, do you speak English?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 74, 'nice to meet you', '/naɪs tə miːt juː/', '🤝', 'Common Phrase', 'mucho gusto / encantado', ARRAY['Hello, nice to meet you!', 'Nice to meet you, I''m Carlos.', 'It''s nice to meet you finally.', 'She said nice to meet you and smiled.', 'Nice to meet you too!', 'He shook my hand and said nice to meet you.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 75, 'see you later', '/siː juː ˈleɪ.tər/', '✌️', 'Common Phrase', 'nos vemos luego', ARRAY['Bye! See you later.', 'See you later at the party.', 'I have to go now. See you later!', 'She waved and said see you later.', 'See you later, have a great day!', 'Okay, see you later then.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 76, 'run', '/rʌn/', '🏃', 'Verb', 'correr', ARRAY['I run in the park every morning.', 'She runs very fast.', 'He ran to catch the bus.', 'The children love to run outside.', 'We ran five kilometers yesterday.', 'Don''t run in the hallway!'], 'ran', '/ræn/', 'run', '/rʌn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 77, 'open', '/ˈoʊ.pən/', '📭', 'Verb', 'abrir', ARRAY['Please open the door.', 'She opened the window.', 'The store opens at nine.', 'He opened his birthday presents.', 'Can you open this jar for me?', 'I opened the book and started reading.'], 'opened', '/ˈoʊ.pənd/', 'opened', '/ˈoʊ.pənd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('a1', 78, 'close', '/kloʊz/', '🔒', 'Verb', 'cerrar', ARRAY['Please close the window.', 'She closed her eyes.', 'The bank closes at five.', 'He closed the door quietly.', 'The store is closed on Sundays.', 'I closed the book and went to sleep.'], 'closed', '/kloʊzd/', 'closed', '/kloʊzd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 79, 'fast', '/fæst/', '⚡', 'Adjective', 'rápido', ARRAY['The car is very fast.', 'She walks very fast.', 'He is a fast runner.', 'Time goes by so fast.', 'The train is faster than the bus.', 'Don''t drive too fast!']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('a1', 80, 'slow', '/sloʊ/', '🐢', 'Adjective', 'lento', ARRAY['The turtle is very slow.', 'Please speak slowly.', 'The bus is too slow.', 'He is a slow reader.', 'Traffic is very slow today.', 'The internet connection is slow.']);

-- ========================
-- Nivel: B2
-- ========================
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 1, 'break down', '/breɪk daʊn/', '💔', 'Phrasal Verb', 'descomponerse / desglosar', ARRAY['My car broke down on the highway.', 'Let me break down the problem for you.', 'She broke down in tears after the news.', 'The washing machine broke down again last night.', 'Can you break down the costs in a simple table?', 'Negotiations broke down after three hours.'], 'broke down', '/broʊk daʊn/', 'broken down', '/ˈbroʊ.kən daʊn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 2, 'bring up', '/brɪŋ ʌp/', '💬', 'Phrasal Verb', 'mencionar / criar', ARRAY['Don''t bring up politics at dinner.', 'She was brought up in a small village.', 'He brought up an interesting point.', 'Why did you bring up that topic again?', 'They were brought up to respect their elders.', 'She keeps bringing up the same issue in every meeting.'], 'brought up', '/brɔːt ʌp/', 'brought up', '/brɔːt ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 3, 'carry out', '/ˈkæri aʊt/', '✅', 'Phrasal Verb', 'llevar a cabo', ARRAY['The team carried out the experiment.', 'We need to carry out a full investigation.', 'She carried out her duties professionally.', 'The surgery was carried out successfully.', 'Police are carrying out door-to-door inquiries.', 'He promised to carry out the reforms.'], 'carried out', '/ˈkærid aʊt/', 'carried out', '/ˈkærid aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 4, 'come across', '/kʌm əˈkrɒs/', '🔍', 'Phrasal Verb', 'encontrarse con / dar la impresión', ARRAY['I came across an old photo album.', 'She comes across as very confident.', 'We came across a beautiful waterfall.', 'Have you ever come across this word before?', 'He came across some valuable information online.', 'She doesn''t come across as the shy type.'], 'came across', '/keɪm əˈkrɒs/', 'come across', '/kʌm əˈkrɒs/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 5, 'cut back', '/kʌt bæk/', '✂️', 'Phrasal Verb', 'reducir / recortar', ARRAY['We need to cut back on expenses.', 'The company cut back its workforce.', 'I''m cutting back on sugar.', 'The government has cut back funding for the arts.', 'She cut back her working hours to spend time with family.', 'If we don''t cut back now, we''ll run out of budget.'], 'cut back', '/kʌt bæk/', 'cut back', '/kʌt bæk/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 6, 'figure out', '/ˈfɪɡər aʊt/', '🧩', 'Phrasal Verb', 'descifrar / resolver', ARRAY['I can''t figure out this puzzle.', 'She figured out the solution quickly.', 'Let''s figure out a plan together.', 'It took me an hour to figure out how to use it.', 'Have you figured out what went wrong?', 'We need to figure out a way to reduce costs.'], 'figured out', '/ˈfɪɡərd aʊt/', 'figured out', '/ˈfɪɡərd aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 7, 'get along', '/ɡet əˈlɒŋ/', '🤝', 'Phrasal Verb', 'llevarse bien', ARRAY['Do you get along with your neighbors?', 'The siblings get along really well.', 'It''s hard to get along with him.', 'We''ve always gotten along despite our differences.', 'How are you getting along in your new job?', 'The two teams get along surprisingly well.'], 'got along', '/ɡɒt əˈlɒŋ/', 'gotten along', '/ˈɡɒt.ən əˈlɒŋ/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 8, 'give up', '/ɡɪv ʌp/', '🏳️', 'Phrasal Verb', 'rendirse / dejar de', ARRAY['Never give up on your dreams.', 'He gave up smoking last year.', 'She refused to give up.', 'I''ve given up trying to convince him.', 'Don''t give up now — you''re almost there.', 'She gave up her seat for an elderly woman.'], 'gave up', '/ɡeɪv ʌp/', 'given up', '/ˈɡɪv.ən ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 9, 'hold on', '/hoʊld ɒn/', '✋', 'Phrasal Verb', 'esperar / agarrarse', ARRAY['Hold on, I''ll be right back.', 'Hold on tight to the railing.', 'Can you hold on for a moment?', 'She held on to the rope as the boat rocked.', 'Hold on — did you just say you''re leaving?', 'He held on to his position despite the pressure.'], 'held on', '/held ɒn/', 'held on', '/held ɒn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 10, 'look forward to', '/lʊk ˈfɔːrwərd tuː/', '🤩', 'Phrasal Verb', 'esperar con ansias', ARRAY['I look forward to meeting you.', 'She''s looking forward to the trip.', 'We look forward to your reply.', 'The kids are looking forward to summer vacation.', 'I''ve been looking forward to this concert for months.', 'He looked forward to retiring and traveling the world.'], 'looked forward to', '/lʊkt ˈfɔːrwərd tuː/', 'looked forward to', '/lʊkt ˈfɔːrwərd tuː/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 11, 'make up', '/meɪk ʌp/', '🎭', 'Phrasal Verb', 'inventar / reconciliarse / maquillarse', ARRAY['He made up an excuse for being late.', 'They argued but made up quickly.', 'Women make up 60% of the workforce.', 'She made up her face before the party.', 'You can''t just make up the rules as you go.', 'They''ve made up their differences and are friends again.'], 'made up', '/meɪd ʌp/', 'made up', '/meɪd ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 12, 'pick up', '/pɪk ʌp/', '📦', 'Phrasal Verb', 'recoger / aprender', ARRAY['Can you pick up the kids from school?', 'She picked up Spanish while living abroad.', 'Business is starting to pick up.', 'I picked up some groceries on the way home.', 'He picks up new languages incredibly fast.', 'The wind picked up speed during the afternoon.'], 'picked up', '/pɪkt ʌp/', 'picked up', '/pɪkt ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 13, 'put off', '/pʊt ɒf/', '⏰', 'Phrasal Verb', 'posponer / desanimar', ARRAY['Stop putting off your homework.', 'The meeting was put off until Monday.', 'His attitude really puts me off.', 'Don''t put off until tomorrow what you can do today.', 'We were put off by the long wait.', 'The game was put off due to heavy rain.'], 'put off', '/pʊt ɒf/', 'put off', '/pʊt ɒf/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 14, 'run into', '/rʌn ˈɪntuː/', '😲', 'Phrasal Verb', 'encontrarse con / chocar', ARRAY['I ran into my old teacher yesterday.', 'We ran into some difficulties.', 'The car ran into a tree.', 'You never know who you''ll run into at these events.', 'The project ran into unexpected delays.', 'I keep running into the same error in my code.'], 'ran into', '/ræn ˈɪntuː/', 'run into', '/rʌn ˈɪntuː/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 15, 'set up', '/set ʌp/', '🔧', 'Phrasal Verb', 'establecer / configurar', ARRAY['She set up her own business.', 'Can you help me set up the equipment?', 'They set up a meeting for Friday.', 'We''ve set up a new system to track orders.', 'The charity was set up to help homeless people.', 'It only takes five minutes to set up the app.'], 'set up', '/set ʌp/', 'set up', '/set ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 16, 'sort out', '/sɔːrt aʊt/', '📋', 'Phrasal Verb', 'resolver / organizar', ARRAY['We need to sort out this mess.', 'I''ll sort out the paperwork tomorrow.', 'Let me sort out the details.', 'Have you sorted out your visa yet?', 'It took a while to sort out the confusion.', 'She sorted out the files by date.'], 'sorted out', '/ˈsɔːr.tɪd aʊt/', 'sorted out', '/ˈsɔːr.tɪd aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 17, 'take over', '/teɪk ˈoʊvər/', '👑', 'Phrasal Verb', 'hacerse cargo / adquirir', ARRAY['She took over the company last year.', 'Can you take over while I''m away?', 'The new manager is taking over on Monday.', 'A large corporation took over the small firm.', 'Who will take over when the director retires?', 'Technology has taken over every aspect of our lives.'], 'took over', '/tʊk ˈoʊvər/', 'taken over', '/ˈteɪ.kən ˈoʊvər/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 18, 'turn down', '/tɜːrn daʊn/', '👎', 'Phrasal Verb', 'rechazar / bajar el volumen', ARRAY['She turned down the job offer.', 'Could you turn down the music?', 'He was turned down for a loan.', 'I can''t believe she turned down a free trip to Paris.', 'The proposal was turned down by the committee.', 'Please turn down the volume — the baby is sleeping.'], 'turned down', '/tɜːrnd daʊn/', 'turned down', '/tɜːrnd daʊn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 19, 'work out', '/wɜːrk aʊt/', '💪', 'Phrasal Verb', 'hacer ejercicio / resolver / funcionar', ARRAY['I work out three times a week.', 'Things will work out in the end.', 'We need to work out a solution.', 'Have you worked out the total cost yet?', 'Their relationship didn''t work out.', 'She works out at the gym every morning.'], 'worked out', '/wɜːrkt aʊt/', 'worked out', '/wɜːrkt aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 20, 'look into', '/lʊk ˈɪntuː/', '🔎', 'Phrasal Verb', 'investigar', ARRAY['The police are looking into the matter.', 'I''ll look into it and get back to you.', 'We should look into cheaper options.', 'Have you looked into the cause of the problem?', 'She looked into several universities before deciding.', 'The committee is looking into the complaints.'], 'looked into', '/lʊkt ˈɪntuː/', 'looked into', '/lʊkt ˈɪntuː/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 21, 'come up with', '/kʌm ʌp wɪð/', '💡', 'Phrasal Verb', 'idear / ocurrírsele', ARRAY['She came up with a brilliant idea.', 'Can you come up with a better plan?', 'He always comes up with excuses.', 'The team came up with an innovative solution.', 'I need to come up with a name for the project.', 'Who came up with this amazing recipe?'], 'came up with', '/keɪm ʌp wɪð/', 'come up with', '/kʌm ʌp wɪð/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 22, 'end up', '/end ʌp/', '🎯', 'Phrasal Verb', 'terminar / acabar', ARRAY['We ended up staying until midnight.', 'If you''re not careful, you''ll end up in trouble.', 'She ended up becoming a doctor.', 'How did we end up talking about this?', 'He ended up accepting the offer after all.', 'We took a wrong turn and ended up in the wrong city.'], 'ended up', '/ˈen.dɪd ʌp/', 'ended up', '/ˈen.dɪd ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 23, 'point out', '/pɔɪnt aʊt/', '👉', 'Phrasal Verb', 'señalar / indicar', ARRAY['She pointed out several errors in the report.', 'I''d like to point out that we''re running late.', 'He pointed out the benefits of the plan.', 'The teacher pointed out the mistake gently.', 'It''s worth pointing out that this is not the first time.', 'She pointed out the risks before we signed the contract.'], 'pointed out', '/ˈpɔɪn.tɪd aʊt/', 'pointed out', '/ˈpɔɪn.tɪd aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 24, 'turn out', '/tɜːrn aʊt/', '🎲', 'Phrasal Verb', 'resultar', ARRAY['It turned out to be a great decision.', 'The weather turned out fine.', 'Things didn''t turn out as expected.', 'As it turned out, he was right all along.', 'The party turned out to be a huge success.', 'It turns out she already knew about the surprise.'], 'turned out', '/tɜːrnd aʊt/', 'turned out', '/tɜːrnd aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 25, 'put up with', '/pʊt ʌp wɪð/', '😤', 'Phrasal Verb', 'tolerar / soportar', ARRAY['I can''t put up with this noise anymore.', 'She puts up with a lot of stress at work.', 'How do you put up with his behavior?', 'We shouldn''t have to put up with this kind of treatment.', 'He put up with the pain until he could see a doctor.', 'I don''t know how she puts up with such long commutes.'], 'put up with', '/pʊt ʌp wɪð/', 'put up with', '/pʊt ʌp wɪð/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 101, 'fall behind', '/fɔːl bɪˈhaɪnd/', '🐢', 'Phrasal Verb', 'quedarse atrás / retrasarse', ARRAY['Don''t fall behind on your payments.', 'She fell behind in her studies after being ill.', 'Our team is falling behind schedule.', 'If you miss classes, you''ll quickly fall behind.', 'The country has fallen behind in technology investment.', 'He fell behind the other runners after the first mile.'], 'fell behind', '/fel bɪˈhaɪnd/', 'fallen behind', '/ˈfɔː.lən bɪˈhaɪnd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 102, 'stand out', '/stænd aʊt/', '🌟', 'Phrasal Verb', 'destacar / sobresalir', ARRAY['Her resume really stands out from the rest.', 'He stood out as the most talented player.', 'Bright colors make the design stand out.', 'One candidate stood out from all the others.', 'What makes your product stand out in the market?', 'She stood out because of her unique approach.'], 'stood out', '/stʊd aʊt/', 'stood out', '/stʊd aʊt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 103, 'back up', '/bæk ʌp/', '💾', 'Phrasal Verb', 'respaldar / hacer copia de seguridad', ARRAY['Always back up your files regularly.', 'Can you back up your claim with evidence?', 'Traffic was backed up for miles.', 'Make sure to back up your data before updating.', 'She backed up her colleague during the meeting.', 'The drain was backed up and flooding the bathroom.'], 'backed up', '/bækt ʌp/', 'backed up', '/bækt ʌp/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 26, 'thorough', '/ˈθʌr.oʊ/', '🔬', 'Adjective', 'minucioso / exhaustivo', ARRAY['She did a thorough investigation.', 'The report was very thorough.', 'He gave the house a thorough cleaning.', 'A thorough review of the evidence is required.', 'The doctor conducted a thorough examination.', 'Be thorough when checking for errors.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 27, 'reluctant', '/rɪˈlʌk.tənt/', '😟', 'Adjective', 'reacio / reticente', ARRAY['He was reluctant to accept the offer.', 'She seemed reluctant to speak.', 'They were reluctant participants.', 'Many employees are reluctant to embrace change.', 'She was reluctant to leave her comfort zone.', 'He gave a reluctant nod of agreement.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 28, 'overwhelming', '/ˌoʊ.vərˈwel.mɪŋ/', '🌊', 'Adjective', 'abrumador', ARRAY['The response was overwhelming.', 'She felt overwhelming sadness.', 'The evidence was overwhelming.', 'The support from the community was overwhelming.', 'He faced an overwhelming amount of paperwork.', 'The smell was overwhelming when we entered the room.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 29, 'appealing', '/əˈpiː.lɪŋ/', '✨', 'Adjective', 'atractivo / atrayente', ARRAY['The idea sounds very appealing.', 'The city is appealing to tourists.', 'It''s not an appealing prospect.', 'She has a very appealing personality.', 'The offer is extremely appealing to young professionals.', 'The packaging makes the product more appealing.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 30, 'genuine', '/ˈdʒen.ju.ɪn/', '💎', 'Adjective', 'genuino / auténtico', ARRAY['She showed genuine concern.', 'Is this painting genuine?', 'He''s a very genuine person.', 'There was a genuine smile on her face.', 'We need genuine commitment, not empty promises.', 'This is a genuine leather bag.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 31, 'straightforward', '/ˌstreɪtˈfɔːr.wərd/', '➡️', 'Adjective', 'directo / sencillo', ARRAY['The instructions are straightforward.', 'He gave a straightforward answer.', 'The process is fairly straightforward.', 'She''s very straightforward — she says what she thinks.', 'The solution was more straightforward than expected.', 'It should be a straightforward task for the team.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 32, 'feasible', '/ˈfiː.zə.bəl/', '🏗️', 'Adjective', 'factible / viable', ARRAY['Is this plan economically feasible?', 'The project is perfectly feasible.', 'We need a more feasible solution.', 'It''s not feasible to finish by Friday.', 'Renewable energy is becoming increasingly feasible.', 'The idea is feasible if we get enough funding.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 33, 'reliable', '/rɪˈlaɪ.ə.bəl/', '🛡️', 'Adjective', 'confiable / fiable', ARRAY['She''s a very reliable employee.', 'This car is extremely reliable.', 'We need reliable data.', 'He''s always been a reliable friend.', 'Is this source reliable enough to cite?', 'A reliable internet connection is essential for remote work.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 34, 'harsh', '/hɑːrʃ/', '❄️', 'Adjective', 'duro / severo', ARRAY['The winter was particularly harsh.', 'His words were very harsh.', 'She faced harsh criticism.', 'The punishment seemed too harsh for such a minor offense.', 'Living conditions in the camp were harsh.', 'Don''t be so harsh on yourself — everyone makes mistakes.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 35, 'subtle', '/ˈsʌt.əl/', '🎨', 'Adjective', 'sutil', ARRAY['There''s a subtle difference between them.', 'She gave a subtle hint.', 'The flavor is quite subtle.', 'He noticed a subtle change in her tone.', 'The film has subtle references to classic literature.', 'The perfume has a subtle floral scent.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 36, 'keen', '/kiːn/', '🦅', 'Adjective', 'entusiasta / agudo', ARRAY['She''s a keen observer.', 'He''s keen on learning Japanese.', 'I''m not keen on the idea.', 'The children were keen to start the project.', 'She has a keen eye for detail.', 'He''s a keen reader who goes through two books a week.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 37, 'remarkable', '/rɪˈmɑːr.kə.bəl/', '🌟', 'Adjective', 'notable / extraordinario', ARRAY['She made a remarkable recovery.', 'The results were truly remarkable.', 'He has a remarkable memory.', 'It''s remarkable how much the city has changed.', 'She showed remarkable courage in the face of danger.', 'The team achieved remarkable success this season.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 38, 'widespread', '/ˈwaɪd.spred/', '🌍', 'Adjective', 'generalizado / extendido', ARRAY['There is widespread concern about pollution.', 'The disease became widespread.', 'The practice is widespread in Asia.', 'Widespread flooding affected thousands of homes.', 'There is widespread agreement that action is needed.', 'The use of social media is now widespread among all ages.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 39, 'controversial', '/ˌkɒn.trəˈvɜː.ʃəl/', '⚡', 'Adjective', 'controvertido / polémico', ARRAY['The decision was highly controversial.', 'He made a controversial statement.', 'It''s a controversial topic.', 'The film was controversial because of its violent scenes.', 'She''s known for her controversial opinions.', 'The new law has proven to be extremely controversial.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 40, 'inevitable', '/ɪˈnev.ɪ.tə.bəl/', '⏳', 'Adjective', 'inevitable', ARRAY['Change is inevitable.', 'The outcome was inevitable.', 'It was inevitable that they''d find out.', 'War seemed inevitable at that point.', 'The inevitable happened — he resigned.', 'Mistakes are inevitable when you''re learning something new.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 41, 'acknowledge', '/əkˈnɒl.ɪdʒ/', '🙏', 'Verb', 'reconocer / admitir', ARRAY['He acknowledged his mistake.', 'The company acknowledged the problem.', 'She acknowledged his contribution.', 'It''s important to acknowledge your feelings.', 'The government acknowledged the need for reform.', 'He refused to acknowledge her presence.'], 'acknowledged', '/əkˈnɒl.ɪdʒd/', 'acknowledged', '/əkˈnɒl.ɪdʒd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 42, 'allocate', '/ˈæl.ə.keɪt/', '📊', 'Verb', 'asignar / destinar', ARRAY['We need to allocate more resources.', 'The funds were allocated to education.', 'How should we allocate the budget?', 'Each department was allocated a specific amount.', 'Time must be allocated wisely during the exam.', 'The manager allocated tasks to each team member.'], 'allocated', '/ˈæl.ə.keɪ.tɪd/', 'allocated', '/ˈæl.ə.keɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 43, 'anticipate', '/ænˈtɪs.ɪ.peɪt/', '🔮', 'Verb', 'anticipar / prever', ARRAY['We anticipate a rise in prices.', 'She anticipated the problem.', 'I didn''t anticipate such a response.', 'The demand was higher than anticipated.', 'We should anticipate potential risks.', 'They anticipated the customers'' needs perfectly.'], 'anticipated', '/ænˈtɪs.ɪ.peɪ.tɪd/', 'anticipated', '/ænˈtɪs.ɪ.peɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 44, 'compromise', '/ˈkɒm.prə.maɪz/', '⚖️', 'Verb', 'llegar a un acuerdo / comprometer', ARRAY['Both sides need to compromise.', 'Don''t compromise your principles.', 'They reached a compromise.', 'Security was compromised during the attack.', 'Neither party was willing to compromise.', 'We compromised on the price after negotiating.'], 'compromised', '/ˈkɒm.prə.maɪzd/', 'compromised', '/ˈkɒm.prə.maɪzd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 45, 'convey', '/kənˈveɪ/', '📨', 'Verb', 'transmitir / comunicar', ARRAY['Words can''t convey my gratitude.', 'The painting conveys a sense of peace.', 'Please convey my regards.', 'He conveyed the message clearly and effectively.', 'Body language can convey more than words.', 'The email failed to convey the urgency of the situation.'], 'conveyed', '/kənˈveɪd/', 'conveyed', '/kənˈveɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 46, 'deceive', '/dɪˈsiːv/', '🎭', 'Verb', 'engañar', ARRAY['He tried to deceive the authorities.', 'Don''t be deceived by appearances.', 'She felt deceived by his promises.', 'The company deceived its customers about the product.', 'He was deceived into signing the contract.', 'Appearances can deceive — things aren''t always what they seem.'], 'deceived', '/dɪˈsiːvd/', 'deceived', '/dɪˈsiːvd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 47, 'demonstrate', '/ˈdem.ən.streɪt/', '📐', 'Verb', 'demostrar', ARRAY['The study demonstrates the link.', 'She demonstrated how to use it.', 'They demonstrated against the policy.', 'The results clearly demonstrate the benefits.', 'He demonstrated exceptional leadership skills.', 'Thousands demonstrated in the streets for change.'], 'demonstrated', '/ˈdem.ən.streɪ.tɪd/', 'demonstrated', '/ˈdem.ən.streɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 48, 'diminish', '/dɪˈmɪn.ɪʃ/', '📉', 'Verb', 'disminuir / reducir', ARRAY['The pain began to diminish.', 'Nothing can diminish her achievement.', 'His influence has diminished over time.', 'The effect of the drug diminishes after a few hours.', 'Their enthusiasm diminished as difficulties arose.', 'Don''t try to diminish her accomplishments.'], 'diminished', '/dɪˈmɪn.ɪʃt/', 'diminished', '/dɪˈmɪn.ɪʃt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 49, 'encounter', '/ɪnˈkaʊn.tər/', '🤝', 'Verb', 'encontrarse con / toparse', ARRAY['We encountered several obstacles.', 'I first encountered this idea in college.', 'She encountered resistance from the team.', 'Have you encountered this problem before?', 'Travelers may encounter delays at the border.', 'They encountered unexpected wildlife on the hike.'], 'encountered', '/ɪnˈkaʊn.tərd/', 'encountered', '/ɪnˈkaʊn.tərd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 50, 'enhance', '/ɪnˈhæns/', '⬆️', 'Verb', 'mejorar / realzar', ARRAY['This will enhance your performance.', 'The lighting enhances the atmosphere.', 'Technology enhances our lives.', 'The new feature enhances the user experience.', 'Music can enhance your mood dramatically.', 'The spices enhanced the flavor of the dish.'], 'enhanced', '/ɪnˈhænst/', 'enhanced', '/ɪnˈhænst/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 51, 'imply', '/ɪmˈplaɪ/', '🤔', 'Verb', 'implicar / insinuar', ARRAY['Are you implying I''m wrong?', 'The data implies a connection.', 'His silence implied agreement.', 'She implied that she wasn''t happy with the decision.', 'The report implies a link between the two factors.', 'I didn''t mean to imply that you were responsible.'], 'implied', '/ɪmˈplaɪd/', 'implied', '/ɪmˈplaɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 52, 'neglect', '/nɪˈɡlekt/', '🚫', 'Verb', 'descuidar / desatender', ARRAY['Don''t neglect your health.', 'The building had been neglected for years.', 'She neglected to mention the cost.', 'Parents who neglect their children face legal consequences.', 'He neglected his duties and was fired.', 'The garden was neglected and overgrown with weeds.'], 'neglected', '/nɪˈɡlek.tɪd/', 'neglected', '/nɪˈɡlek.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 53, 'perceive', '/pərˈsiːv/', '👁️', 'Verb', 'percibir', ARRAY['How do others perceive you?', 'She perceived a change in his behavior.', 'The threat was perceived as serious.', 'He perceived the comment as an insult.', 'The way we perceive the world shapes our behavior.', 'She quickly perceived that something was wrong.'], 'perceived', '/pərˈsiːvd/', 'perceived', '/pərˈsiːvd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 54, 'pursue', '/pərˈsuː/', '🏃', 'Verb', 'perseguir / dedicarse a', ARRAY['She decided to pursue a career in law.', 'The police pursued the suspect.', 'He pursued his dream relentlessly.', 'We will pursue legal action if necessary.', 'She pursued her studies despite financial difficulties.', 'The company is pursuing new markets in Asia.'], 'pursued', '/pərˈsuːd/', 'pursued', '/pərˈsuːd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 55, 'reveal', '/rɪˈviːl/', '🎁', 'Verb', 'revelar / desvelar', ARRAY['The investigation revealed the truth.', 'She revealed her plans to the team.', 'The data reveals an interesting pattern.', 'He revealed a secret he had kept for years.', 'The survey revealed surprising customer preferences.', 'The curtain was pulled back to reveal the new product.'], 'revealed', '/rɪˈviːld/', 'revealed', '/rɪˈviːld/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 56, 'tackle', '/ˈtæk.əl/', '🏈', 'Verb', 'abordar / enfrentar', ARRAY['We need to tackle this problem head-on.', 'The government is tackling unemployment.', 'She tackled the challenge with enthusiasm.', 'He tackled the attacker and held him down.', 'The team tackled the project with determination.', 'How should we tackle this issue effectively?'], 'tackled', '/ˈtæk.əld/', 'tackled', '/ˈtæk.əld/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 57, 'undergo', '/ˌʌn.dərˈɡoʊ/', '🔄', 'Verb', 'someterse a / experimentar', ARRAY['He underwent surgery last week.', 'The city has undergone major changes.', 'Applicants must undergo a background check.', 'The system is undergoing maintenance.', 'She underwent extensive training before the mission.', 'The building has undergone significant renovations.'], 'underwent', '/ˌʌn.dərˈwent/', 'undergone', '/ˌʌn.dərˈɡɒn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 58, 'withdraw', '/wɪðˈdrɔː/', '🏧', 'Verb', 'retirar(se)', ARRAY['She withdrew money from the ATM.', 'The troops were withdrawn.', 'He withdrew from the competition.', 'The offer was withdrawn after the deadline.', 'She has become withdrawn since the incident.', 'They decided to withdraw their application.'], 'withdrew', '/wɪðˈdruː/', 'withdrawn', '/wɪðˈdrɔːn/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 59, 'yield', '/jiːld/', '🌾', 'Verb', 'producir / ceder', ARRAY['The experiment yielded interesting results.', 'The tree yields fruit every summer.', 'He refused to yield to pressure.', 'The investment yielded a high return.', 'She finally yielded to their demands.', 'Good soil yields better crops.'], 'yielded', '/ˈjiːl.dɪd/', 'yielded', '/ˈjiːl.dɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 60, 'grasp', '/ɡræsp/', '✊', 'Verb', 'agarrar / comprender', ARRAY['She grasped the concept quickly.', 'He grasped her hand tightly.', 'I couldn''t grasp what he meant.', 'It took me a while to grasp the full picture.', 'The child grasped the toy and wouldn''t let go.', 'Some students struggle to grasp abstract ideas.'], 'grasped', '/ɡræspt/', 'grasped', '/ɡræspt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 61, 'drawback', '/ˈdrɔː.bæk/', '⚠️', 'Noun', 'desventaja / inconveniente', ARRAY['The main drawback is the cost.', 'Every plan has its drawbacks.', 'One drawback of living here is the traffic.', 'Despite its drawbacks, the software is widely used.', 'The only drawback is the lack of parking.', 'Cost remains the biggest drawback of the technology.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 62, 'outcome', '/ˈaʊt.kʌm/', '🎯', 'Noun', 'resultado', ARRAY['The outcome of the election was surprising.', 'We''re waiting for the outcome.', 'A positive outcome is expected.', 'The outcome depends on several factors.', 'Nobody could have predicted this outcome.', 'What was the outcome of the negotiations?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 63, 'insight', '/ˈɪn.saɪt/', '💡', 'Noun', 'perspicacia / perspectiva', ARRAY['The book provides valuable insights.', 'She has great insight into human nature.', 'His insights shaped the project.', 'The data offers interesting insights into customer behavior.', 'He shared some insights from his years of experience.', 'This report provides insight into market trends.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 64, 'awareness', '/əˈwer.nəs/', '🧠', 'Noun', 'conciencia / conocimiento', ARRAY['There''s growing awareness of the issue.', 'Raise awareness about climate change.', 'Self-awareness is key to growth.', 'The campaign increased public awareness significantly.', 'Environmental awareness is taught from a young age.', 'She has a strong awareness of cultural differences.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 65, 'breakthrough', '/ˈbreɪk.θruː/', '🚀', 'Noun', 'avance / gran descubrimiento', ARRAY['Scientists made a major breakthrough.', 'This was a breakthrough in negotiations.', 'The breakthrough came after years of research.', 'Medical breakthroughs are saving millions of lives.', 'It was a real breakthrough moment for the team.', 'The company announced a breakthrough in battery technology.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 66, 'constraint', '/kənˈstreɪnt/', '🔗', 'Noun', 'restricción / limitación', ARRAY['Budget constraints limit our options.', 'Time is a major constraint.', 'We must work within these constraints.', 'Legal constraints prevented them from proceeding.', 'The project was completed despite several constraints.', 'Financial constraints forced us to rethink our strategy.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 67, 'emphasis', '/ˈem.fə.sɪs/', '❗', 'Noun', 'énfasis', ARRAY['The emphasis is on quality.', 'She placed great emphasis on education.', 'There''s a growing emphasis on sustainability.', 'He spoke with emphasis, making his point very clear.', 'The emphasis has shifted from quantity to quality.', 'We need to put more emphasis on customer satisfaction.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 68, 'framework', '/ˈfreɪm.wɜːrk/', '🏛️', 'Noun', 'marco / estructura', ARRAY['We need a legal framework for this.', 'The framework guides our decisions.', 'He developed a theoretical framework.', 'The company operates within a strict regulatory framework.', 'This framework helps organize the research process.', 'A solid framework is essential for project success.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 69, 'controversy', '/ˈkɒn.trə.vɜː.si/', '🔥', 'Noun', 'controversia / polémica', ARRAY['The policy caused great controversy.', 'There''s controversy surrounding the decision.', 'He tried to avoid controversy.', 'The controversy attracted widespread media attention.', 'She found herself at the center of a major controversy.', 'The book sparked controversy among religious groups.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 70, 'likelihood', '/ˈlaɪ.kli.hʊd/', '📈', 'Noun', 'probabilidad', ARRAY['There''s a strong likelihood of rain.', 'In all likelihood, he''ll agree.', 'The likelihood of success is high.', 'What is the likelihood of this happening again?', 'The likelihood of a recession has increased.', 'In all likelihood, the flight will be delayed.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 71, 'setback', '/ˈset.bæk/', '🚧', 'Noun', 'contratiempo / revés', ARRAY['The project suffered a major setback.', 'Despite setbacks, she persevered.', 'It was only a temporary setback.', 'Every setback is a learning opportunity.', 'The team recovered quickly from the setback.', 'Financial setbacks delayed the launch by six months.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 72, 'prospect', '/ˈprɒs.pekt/', '🔭', 'Noun', 'perspectiva / posibilidad', ARRAY['The prospect of promotion excited her.', 'Job prospects are improving.', 'It''s an exciting prospect.', 'The prospect of moving abroad was thrilling.', 'Career prospects in tech are excellent right now.', 'He wasn''t enthusiastic about the prospect of working weekends.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 73, 'assumption', '/əˈsʌmp.ʃən/', '💭', 'Noun', 'suposición', ARRAY['We can''t make that assumption.', 'The assumption proved to be wrong.', 'Challenge your assumptions.', 'It''s a common assumption that experience equals skill.', 'Her assumptions were based on incomplete data.', 'Don''t make assumptions about people you''ve never met.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 74, 'disruption', '/dɪsˈrʌp.ʃən/', '💥', 'Noun', 'interrupción / alteración', ARRAY['The storm caused major disruption.', 'Digital disruption is reshaping industries.', 'We apologize for the disruption.', 'Supply chain disruption affected global markets.', 'The strike caused serious disruption to public transport.', 'Technological disruption is both a challenge and an opportunity.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 75, 'consensus', '/kənˈsen.səs/', '🤝', 'Noun', 'consenso', ARRAY['We reached a consensus on the issue.', 'There''s no consensus among experts.', 'The consensus is that it''s too risky.', 'Building consensus takes time and patience.', 'The scientific consensus supports the theory.', 'It''s hard to reach consensus when opinions are so divided.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 76, 'presumably', '/prɪˈzuː.mə.bli/', '🤷', 'Adverb', 'presumiblemente', ARRAY['Presumably, he''ll arrive by noon.', 'She was presumably aware of the risk.', 'They had presumably left earlier.', 'Presumably, the meeting has been rescheduled.', 'He''s presumably the one responsible for this decision.', 'She presumably already knows about the changes.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 77, 'merely', '/ˈmɪr.li/', '👐', 'Adverb', 'simplemente / meramente', ARRAY['I was merely suggesting an idea.', 'It''s merely a matter of time.', 'He merely nodded in response.', 'She''s merely trying to help.', 'This is merely the beginning of the process.', 'I merely pointed out the obvious — I wasn''t criticizing.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 78, 'roughly', '/ˈrʌf.li/', '📏', 'Adverb', 'aproximadamente / bruscamente', ARRAY['It costs roughly $500.', 'Roughly half the population agreed.', 'He roughly pushed the door open.', 'The project will take roughly six months.', 'Roughly speaking, a third of employees are remote.', 'She roughly estimated the distance at two miles.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 79, 'thoroughly', '/ˈθʌr.ə.li/', '🧹', 'Adverb', 'a fondo / completamente', ARRAY['She thoroughly enjoyed the show.', 'Clean the surface thoroughly.', 'The plan was thoroughly reviewed.', 'Make sure to read the instructions thoroughly.', 'I was thoroughly impressed by her presentation.', 'The police thoroughly searched the building.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 80, 'considerably', '/kənˈsɪd.ər.ə.bli/', '📊', 'Adverb', 'considerablemente', ARRAY['Prices have increased considerably.', 'She''s considerably older than him.', 'The situation has improved considerably.', 'The cost was considerably higher than expected.', 'Her performance has improved considerably this year.', 'The new version is considerably faster than the old one.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 81, 'apparently', '/əˈpær.ənt.li/', '🗞️', 'Adverb', 'aparentemente / al parecer', ARRAY['Apparently, they''ve moved to London.', 'She apparently forgot about the meeting.', 'The issue is apparently resolved.', 'Apparently, the restaurant is closing next month.', 'He was apparently unaware of the changes.', 'The system apparently crashed due to a software bug.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 82, 'meanwhile', '/ˈmiːn.waɪl/', '⏯️', 'Adverb', 'mientras tanto', ARRAY['Meanwhile, the situation was getting worse.', 'She studied; meanwhile, he played games.', 'Meanwhile, back at the office...', 'The boss was in a meeting; meanwhile, we finished the report.', 'Meanwhile, tensions between the two countries continued to rise.', 'You start cooking; meanwhile, I''ll set the table.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 83, 'nevertheless', '/ˌnev.ər.ðəˈles/', '↪️', 'Adverb', 'sin embargo / no obstante', ARRAY['It was risky; nevertheless, we proceeded.', 'She was tired, but nevertheless kept working.', 'Nevertheless, the results were promising.', 'The weather was terrible; nevertheless, they enjoyed the trip.', 'He had no experience; nevertheless, he got the job.', 'The plan had flaws; nevertheless, it was approved.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 84, 'ultimately', '/ˈʌl.tɪ.mət.li/', '🏁', 'Adverb', 'en última instancia / finalmente', ARRAY['Ultimately, the decision is yours.', 'It ultimately led to success.', 'They ultimately agreed to the terms.', 'Ultimately, what matters is customer satisfaction.', 'The project was ultimately cancelled due to budget cuts.', 'She ultimately decided to pursue a different career.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 85, 'solely', '/ˈsoʊl.li/', '☝️', 'Adverb', 'únicamente / exclusivamente', ARRAY['The blame lies solely with management.', 'I''m solely responsible for this.', 'Success depends solely on effort.', 'This product is made solely from natural ingredients.', 'He focuses solely on results.', 'The decision was solely based on merit.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 86, 'cope', '/koʊp/', '🧘', 'Verb', 'lidiar / arreglárselas', ARRAY['She coped well with the pressure.', 'How do you cope with stress?', 'It''s hard to cope with loss.', 'The team coped admirably with the sudden changes.', 'He couldn''t cope with the workload anymore.', 'Learning to cope with failure is part of growing up.'], 'coped', '/koʊpt/', 'coped', '/koʊpt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 87, 'praise', '/preɪz/', '👏', 'Noun/Verb', 'elogio / elogiar', ARRAY['The teacher praised his efforts.', 'She deserves praise for her work.', 'The film received widespread praise.', 'His performance was praised by critics worldwide.', 'Don''t forget to praise your team when they do well.', 'The initiative has been praised as a model for other cities.'], 'praised', '/preɪzd/', 'praised', '/preɪzd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 88, 'adequate', '/ˈæd.ɪ.kwət/', '✔️', 'Adjective', 'adecuado / suficiente', ARRAY['The facilities are barely adequate.', 'We need adequate funding.', 'Is this an adequate response?', 'The salary is adequate but not generous.', 'Adequate preparation is key to success.', 'The building doesn''t have adequate ventilation.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 89, 'substantial', '/səbˈstæn.ʃəl/', '🏔️', 'Adjective', 'sustancial / considerable', ARRAY['They made a substantial investment.', 'There''s a substantial difference.', 'She earns a substantial salary.', 'The company made a substantial profit this quarter.', 'We need substantial evidence to support this claim.', 'A substantial number of people attended the event.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 90, 'abolish', '/əˈbɒl.ɪʃ/', '🗑️', 'Verb', 'abolir / eliminar', ARRAY['The law was abolished in 1990.', 'They want to abolish the death penalty.', 'Slavery was abolished long ago.', 'The committee voted to abolish the outdated regulations.', 'Several countries have abolished the monarchy.', 'There''s a growing movement to abolish standardized testing.'], 'abolished', '/əˈbɒl.ɪʃt/', 'abolished', '/əˈbɒl.ɪʃt/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 91, 'ambiguous', '/æmˈbɪɡ.ju.əs/', '❓', 'Adjective', 'ambiguo', ARRAY['The statement was deliberately ambiguous.', 'The rules are somewhat ambiguous.', 'His answer was ambiguous.', 'The contract contained ambiguous language.', 'Ambiguous instructions led to confusion.', 'The ending of the film was intentionally ambiguous.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 92, 'compensate', '/ˈkɒm.pen.seɪt/', '💰', 'Verb', 'compensar / indemnizar', ARRAY['The company compensated the victims.', 'Nothing can compensate for the loss.', 'He was fairly compensated.', 'Workers should be compensated for overtime hours.', 'She tried to compensate for her lack of experience.', 'The insurance company refused to compensate the damage.'], 'compensated', '/ˈkɒm.pen.seɪ.tɪd/', 'compensated', '/ˈkɒm.pen.seɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 93, 'prospect', '/ˈprɒs.pekt/', '🌅', 'Noun', 'perspectiva / posibilidad', ARRAY['Job prospects are looking good.', 'The prospect of change excites me.', 'There''s little prospect of improvement.', 'He''s a promising prospect for the national team.', 'The economic prospects for next year are uncertain.', 'She''s excited about the prospect of studying abroad.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 94, 'contemplate', '/ˈkɒn.tem.pleɪt/', '🤔', 'Verb', 'contemplar / considerar', ARRAY['She contemplated her options carefully.', 'I''ve been contemplating a career change.', 'He sat contemplating the view.', 'Have you ever contemplated what life would be like abroad?', 'The company is contemplating a merger.', 'She contemplated the painting for a long time.'], 'contemplated', '/ˈkɒn.tem.pleɪ.tɪd/', 'contemplated', '/ˈkɒn.tem.pleɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 95, 'vulnerable', '/ˈvʌl.nər.ə.bəl/', '🥀', 'Adjective', 'vulnerable', ARRAY['Children are especially vulnerable.', 'The system is vulnerable to attacks.', 'She felt vulnerable after the breakup.', 'Elderly people are more vulnerable to illness.', 'The exposed wires make the network vulnerable.', 'Being vulnerable doesn''t mean being weak.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 96, 'initiative', '/ɪˈnɪʃ.ə.tɪv/', '🚀', 'Noun', 'iniciativa', ARRAY['She took the initiative to organize it.', 'The government launched a new initiative.', 'Show some initiative!', 'The company''s green initiative reduced waste by 40%.', 'He lacks initiative and always waits for instructions.', 'This initiative aims to support small businesses.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 97, 'legitimate', '/lɪˈdʒɪt.ɪ.mət/', '📜', 'Adjective', 'legítimo', ARRAY['That''s a legitimate concern.', 'Is this a legitimate business?', 'She has a legitimate claim.', 'His frustration is completely legitimate.', 'We only work with legitimate suppliers.', 'The question is whether this approach is legitimate.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 98, 'obstacle', '/ˈɒb.stə.kəl/', '🧱', 'Noun', 'obstáculo', ARRAY['Lack of funding is a major obstacle.', 'She overcame many obstacles.', 'Don''t let obstacles stop you.', 'Bureaucracy is the biggest obstacle to progress.', 'They faced numerous obstacles during the project.', 'Language can be an obstacle when traveling abroad.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 99, 'stimulate', '/ˈstɪm.jə.leɪt/', '⚡', 'Verb', 'estimular', ARRAY['Exercise stimulates the brain.', 'We need to stimulate economic growth.', 'The discussion stimulated new ideas.', 'Coffee stimulates the nervous system.', 'The government plans to stimulate job creation.', 'Reading stimulates creativity and imagination.'], 'stimulated', '/ˈstɪm.jə.leɪ.tɪd/', 'stimulated', '/ˈstɪm.jə.leɪ.tɪd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 100, 'precisely', '/prɪˈsaɪs.li/', '🎯', 'Adverb', 'precisamente / exactamente', ARRAY['That''s precisely what I mean.', 'She arrived at precisely 3 PM.', 'Measure the ingredients precisely.', 'This is precisely the kind of thing we need to avoid.', 'He described the process precisely and clearly.', 'The meeting started at precisely ten o''clock.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 104, 'entail', '/ɪnˈteɪl/', '📝', 'Verb', 'implicar / conllevar', ARRAY['What does the job entail exactly?', 'The project entails a lot of research.', 'This decision entails certain risks.', 'Do you understand what the position entails?', 'The renovation entailed months of hard work.', 'Moving abroad entails a big lifestyle change.'], 'entailed', '/ɪnˈteɪld/', 'entailed', '/ɪnˈteɪld/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 105, 'scarce', '/skers/', '🏜️', 'Adjective', 'escaso', ARRAY['Clean water is scarce in that region.', 'Resources became increasingly scarce.', 'Jobs are scarce in rural areas.', 'Food was scarce during the winter months.', 'Skilled workers are scarce in this industry.', 'Time is a scarce resource for most people.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 106, 'trait', '/treɪt/', '🧬', 'Noun', 'rasgo / característica', ARRAY['Honesty is his best trait.', 'Leadership traits can be developed.', 'The trait is passed down genetically.', 'Patience is a valuable trait in a teacher.', 'She inherited many traits from her mother.', 'What personality traits do you value most?']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 107, 'exempt', '/ɪɡˈzempt/', '🎫', 'Adjective', 'exento / libre de', ARRAY['Students are exempt from the tax.', 'No one is exempt from the rules.', 'The organization is exempt from paying fees.', 'Small businesses may be exempt from certain regulations.', 'Military personnel are exempt from this requirement.', 'Charitable organizations are often exempt from taxation.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 108, 'pledge', '/pledʒ/', '🤞', 'Noun/Verb', 'promesa / comprometerse', ARRAY['He pledged to support the cause.', 'The company made a pledge to reduce emissions.', 'They pledged $1 million to charity.', 'She pledged her loyalty to the organization.', 'World leaders pledged to take action on climate change.', 'He fulfilled his pledge to the community.'], 'pledged', '/pledʒd/', 'pledged', '/pledʒd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples, past, past_pron, pp, pp_pron)
VALUES ('b2', 109, 'hinder', '/ˈhɪn.dər/', '🚧', 'Verb', 'obstaculizar / dificultar', ARRAY['Bad weather hindered rescue efforts.', 'Don''t let fear hinder your progress.', 'Lack of funding hindered the project.', 'Bureaucracy often hinders innovation.', 'Poor communication hindered the team''s performance.', 'The injury hindered her ability to compete.'], 'hindered', '/ˈhɪn.dərd/', 'hindered', '/ˈhɪn.dərd/');
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 110, 'supposedly', '/səˈpoʊ.zɪd.li/', '🗣️', 'Adverb', 'supuestamente', ARRAY['He supposedly left the country last week.', 'The restaurant is supposedly the best in town.', 'She was supposedly an expert in the field.', 'The product is supposedly eco-friendly.', 'They supposedly have the best customer service.', 'He''s supposedly fluent in five languages.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 111, 'cut the cheese', '/kʌt ðə tʃiːz/', '🧀', 'Common Phrase', 'echarse un gas (coloquial / humorístico)', ARRAY['Someone cut the cheese in the elevator.', 'Don''t cut the cheese in public, please!', 'He cut the cheese and blamed the dog.', 'We all knew who cut the cheese at dinner.', 'She couldn''t stop laughing after someone cut the cheese.', 'If you cut the cheese, at least open a window.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 112, 'get over it', '/ɡɛt ˈoʊ.vər/', '💪', 'Common Phrase', 'superar / recuperarse de', ARRAY['It took her months to get over the breakup.', 'You need to get over your fear of flying.', 'I can''t get over how beautiful this place is.', 'He finally got over his cold after a week.', 'She never really got over losing that job.', 'Get over it — it happened years ago!']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 113, 'blow your mind', '/bloʊ jɔːr maɪnd/', '🤯', 'Common Phrase', 'volar la cabeza / impresionar mucho', ARRAY['This movie will blow your mind.', 'The magic trick totally blew my mind.', 'Wait until you taste this — it''ll blow your mind.', 'The concert blew everyone''s mind last night.', 'The plot twist at the end blew my mind.', 'Science facts that will blow your mind.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 114, 'jog your memory', '/dʒɑːɡ jɔːr ˈmɛm.ər.i/', '🧠', 'Common Phrase', 'refrescar la memoria', ARRAY['Let me show you a photo to jog your memory.', 'Does this name jog your memory at all?', 'Maybe visiting the old house will jog your memory.', 'The song jogged her memory of that summer.', 'I''ll give you a hint to jog your memory.', 'Seeing his face jogged my memory immediately.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 115, 'cut corners', '/kʌt ˈkɔːr.nərz/', '✂️', 'Common Phrase', 'tomar atajos / hacer algo de forma barata', ARRAY['The builder cut corners and the roof started leaking.', 'Don''t cut corners on safety procedures.', 'They cut corners to save money on the project.', 'If you cut corners, quality will suffer.', 'The company was fined for cutting corners.', 'We can''t afford to cut corners on this one.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 116, 'walk all over someone', '/wɔːk ɔːl ˈoʊ.vər/', '🚶', 'Common Phrase', 'aprovecharse de alguien / pisotear', ARRAY['Don''t let your boss walk all over you.', 'She realized her friends were walking all over her.', 'He walks all over people who can''t say no.', 'Stop letting them walk all over you!', 'If you don''t stand up, they''ll walk all over you.', 'She used to walk all over him until he spoke up.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 117, 'hit the hay', '/hɪt ðə heɪ/', '🛏️', 'Common Phrase', 'irse a dormir / acostarse', ARRAY['I''m exhausted — time to hit the hay.', 'We should hit the hay early tonight.', 'He hit the hay as soon as he got home.', 'Let''s hit the hay, we have an early flight.', 'She hit the hay right after dinner.', 'I usually hit the hay around 11 PM.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 118, 'spill the beans', '/spɪl ðə biːnz/', '🫘', 'Common Phrase', 'revelar un secreto / soltar la sopa', ARRAY['Come on, spill the beans! What happened?', 'She accidentally spilled the beans about the surprise party.', 'Don''t spill the beans — it''s a secret!', 'Who spilled the beans to the press?', 'He spilled the beans before we could stop him.', 'I promise I won''t spill the beans.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 119, 'bite the bullet', '/baɪt ðə ˈbʊl.ɪt/', '😬', 'Common Phrase', 'aceptar algo difícil / armarse de valor', ARRAY['I decided to bite the bullet and ask for a raise.', 'Sometimes you just have to bite the bullet.', 'She bit the bullet and went to the dentist.', 'We bit the bullet and sold the house.', 'It''s time to bite the bullet and make a decision.', 'He bit the bullet and apologized to his ex.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 120, 'under the weather', '/ˈʌn.dər ðə ˈwɛð.ər/', '🤒', 'Common Phrase', 'sentirse mal / indispuesto', ARRAY['I''m feeling a bit under the weather today.', 'She''s been under the weather all week.', 'He called in sick — he''s under the weather.', 'If you''re under the weather, stay home and rest.', 'I was under the weather, so I skipped the gym.', 'She looked a little under the weather at the meeting.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 121, 'break the ice', '/breɪk ðə aɪs/', '🧊', 'Common Phrase', 'romper el hielo', ARRAY['He told a joke to break the ice at the party.', 'Let''s play a game to break the ice.', 'It''s always hard to break the ice with strangers.', 'She broke the ice by complimenting his shirt.', 'A simple question can help break the ice.', 'The team-building activity broke the ice quickly.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 122, 'the last straw', '/ðə læst strɔː/', '🥤', 'Common Phrase', 'la gota que colmó el vaso', ARRAY['Being late again was the last straw for his boss.', 'That comment was the last straw — I''m leaving.', 'The broken promise was the last straw in their marriage.', 'Missing the deadline was the last straw.', 'For many employees, the pay cut was the last straw.', 'Her rudeness was the last straw for the manager.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 123, 'a piece of cake', '/ə piːs əv keɪk/', '🍰', 'Common Phrase', 'pan comido / muy fácil', ARRAY['The exam was a piece of cake!', 'Don''t worry, this task is a piece of cake.', 'For her, cooking is a piece of cake.', 'Learning to drive was a piece of cake for him.', 'The first level of the game is a piece of cake.', 'It''s not going to be a piece of cake, trust me.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 124, 'cost an arm and a leg', '/kɔːst ən ɑːrm ənd ə lɛɡ/', '💸', 'Common Phrase', 'costar un ojo de la cara / ser carísimo', ARRAY['That handbag must have cost an arm and a leg.', 'Repairs on old cars can cost an arm and a leg.', 'The wedding cost us an arm and a leg.', 'Living in New York costs an arm and a leg.', 'The lawyer''s fees cost an arm and a leg.', 'A good education shouldn''t cost an arm and a leg.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 125, 'once in a blue moon', '/wʌns ɪn ə bluː muːn/', '🌙', 'Common Phrase', 'muy rara vez / de vez en cuando', ARRAY['I only eat fast food once in a blue moon.', 'She visits her hometown once in a blue moon.', 'Opportunities like this come once in a blue moon.', 'We go to the cinema once in a blue moon.', 'He calls his parents once in a blue moon.', 'A sale like this happens once in a blue moon.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 126, 'burn the midnight oil', '/bɜːrn ðə ˈmɪd.naɪt ɔɪl/', '🕯️', 'Common Phrase', 'trasnochar trabajando / quemarse las pestañas', ARRAY['She burned the midnight oil studying for finals.', 'We had to burn the midnight oil to meet the deadline.', 'He''s been burning the midnight oil all week.', 'I don''t want to burn the midnight oil again tonight.', 'The developers burned the midnight oil before the launch.', 'If you keep burning the midnight oil, you''ll get sick.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 127, 'let the cat out of the bag', '/lɛt ðə kæt aʊt əv ðə bæɡ/', '🐱', 'Common Phrase', 'revelar un secreto sin querer', ARRAY['He let the cat out of the bag about the surprise party.', 'Don''t let the cat out of the bag — it''s a secret!', 'She accidentally let the cat out of the bag.', 'Who let the cat out of the bag about the promotion?', 'I almost let the cat out of the bag during dinner.', 'Try not to let the cat out of the bag before Friday.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 128, 'go the extra mile', '/ɡoʊ ðə ˈɛk.strə maɪl/', '🏃', 'Common Phrase', 'hacer un esfuerzo extra / dar la milla extra', ARRAY['She always goes the extra mile for her clients.', 'If you go the extra mile, people will notice.', 'The teacher went the extra mile to help the student.', 'Great companies go the extra mile for customer service.', 'He went the extra mile and stayed late to finish.', 'Going the extra mile is what separates good from great.']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 129, 'sit on the fence', '/sɪt ɒn ðə fɛns/', '🤷', 'Common Phrase', 'no decidirse / estar indeciso', ARRAY['Stop sitting on the fence and make a decision.', 'He''s been sitting on the fence about the job offer.', 'You can''t sit on the fence forever.', 'Politicians often sit on the fence on controversial topics.', 'She sat on the fence until the last minute.', 'Don''t sit on the fence — pick a side!']);
INSERT INTO words (level_id, word_index, word, pron, emoji, cat, es, examples)
VALUES ('b2', 130, 'pull someone''s leg', '/pʊl ˈsʌm.wʌnz lɛɡ/', '😜', 'Common Phrase', 'tomarle el pelo a alguien / bromear', ARRAY['Are you pulling my leg, or is that true?', 'He loves pulling people''s legs with fake stories.', 'I thought she was pulling my leg at first.', 'Don''t pull my leg — tell me the truth!', 'They were just pulling your leg, don''t worry.', 'She pulled his leg about winning the lottery.']);

COMMIT;
